### ISSUE TITLE
Identify Bug with Serial Devices Not Showing 

### ISSUE THREAD

**Issue by spiceywasabi** [O-MG/WebFlasher#20]
Several users have experienced a successful flash via the Python flash.py tool, however they have no success with the Web Flasher. 

Additional testing has identified two cases:

1. User has no serial devices visible (may be permission error and we need to have a UI prompt to alert to how to fix this)
2. User can see their serial device but its currently filtered

Need to identify the root cause on this since the filter matches the Silicon Devices VID

**Comment by SYGINT** [comment]
I had this issue before on Ubuntu and then on Arch, I solved this by `chown`ing `/dev/ttyUSB0`, not sure this is acceptable practice, though? I had no issues with this on Windows 10, however.

**Comment by spiceywasabi** [comment]
@SYGINT this issue focuses on the device not being detected by the javascript but being found if no filters are applied and permission issues on mac and windows we haven't identified yet
